title: "Foldable Robotics Portfolio"
description: "Projects for Foldable Robotics â€“ MuJoCo, four-bar mechanism, and jumping robots."
theme: minima

# Optional: your GitHub username and repo (for footer links)
github_username: your-github-username
repository: your-github-username/your-repo-name
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
