title: "Foldable Robotics Portfolio"
description: "Project 1 proposal and Project 2 final robot for Foldable Robotics."

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

search_enabled: true

# Optional: later you can enable custom CSS like this:
 just_the_docs:
   custom_css:
     - "/assets/css/custom.css"
